services:
  - type: web
    name: preciomed
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PRECIOMED_USERNAME
        value: admin
      - key: PRECIOMED_SECRET_KEY
        generateValue: true
      - key: MAX_USERS
        value: 100000
